"""empty message

Revision ID: 075345657519
Revises: 
Create Date: 2019-05-05 09:37:27.044844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075345657519'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registerinterest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registerinterest')
    # ### end Alembic commands ###
