"""empty message

Revision ID: 7c538582fdc2
Revises: 
Create Date: 2019-12-14 23:52:29.018966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c538582fdc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('establishments', 'establishment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('establishments', 'latitude',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('establishments', 'longitude',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('establishments', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ratings', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ratings', 'eid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'placename',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ratings', 'rater',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ratings', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'pwdhash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'pwdhash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ratings', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'rater',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ratings', 'placename',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ratings', 'eid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('establishments', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('establishments', 'longitude',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('establishments', 'latitude',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('establishments', 'establishment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
